[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "panda-graphkit"
version = "0.1.0"
description = "A DCC-independent graph and expression system for procedural animation."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Joseph Chou" }
]
dependencies = []

[tool.setuptools.packages.find]
include = ["panda_graphkit*"]